// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuhpzuevzvjmgtbzpkpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aHB6dWV2enZqbWd0Ynpwa3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTQ2MjgsImV4cCI6MjA1NzE3MDYyOH0.YI05fQ6-mNrq3eGdNhMxprEfxDkolJREuoqwa7bDmkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);